version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: astro
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
    
      - OLLAMA_MODELS=nomic-embed-text
    restart: unless-stopped

volumes:
  ollama_data:
# deepcoder:14b